logging: #logback config
  config: classpath:logback-spring.xml
  file: logs/spring-boot.log
  level.: info
  


datasource:
#mysql
  source:
#    url: jdbc:mysql://114.55.43.54:3306/pop?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://192.168.20.10:3306/pop?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1111ssSS
    driverClassName: com.mysql.jdbc.Driver
    
 #oracle   
  dest:
     url: jdbc:oracle:thin:@192.168.20.7:1521:CRMLS
     username: dbusrvip
     password: futurevip
     driverClassName: oracle.jdbc.driver.OracleDriver
     
     

     
   
 
      

    
  main:
    banner-mode: "off"



